import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://cfffoclrpsxldfhsofha.supabase.co';
const SUPABASE_KEY='sb_publishable_LOgq_zm7n7p6LFeOyIIhfg_xai-sh4p';
const LEVEL=50;
const SPRITE=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/${id}.png`;
const ART=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
const TYPE_ORDER=['normal','fire','water','electric','grass','ice','fighting','poison','ground','flying','psychic','bug','rock','ghost','dragon'];
const PHYSICAL=new Set(['normal','fighting','flying','poison','ground','rock','bug','ghost']);
const GEN1_MOVE_TYPE_OVERRIDES={bite:'normal',gust:'normal','karate-chop':'normal','sand-attack':'ground','razor-wind':'normal',struggle:'normal'};
const TYPE_CHART={
 normal:{rock:.5,ghost:0},fire:{fire:.5,water:.5,grass:2,ice:2,bug:2,rock:.5,dragon:.5},water:{fire:2,water:.5,grass:.5,ground:2,rock:2,dragon:.5},electric:{water:2,electric:.5,grass:.5,ground:0,flying:2,dragon:.5},grass:{fire:.5,water:2,grass:.5,poison:.5,ground:2,flying:.5,bug:.5,rock:2,dragon:.5},ice:{fire:.5,water:.5,grass:2,ice:.5,ground:2,flying:2,dragon:2},fighting:{normal:2,poison:.5,flying:.5,psychic:.5,bug:.5,rock:2,ghost:0},poison:{grass:2,poison:.5,ground:.5,bug:2,rock:.5,ghost:.5},ground:{fire:2,electric:2,grass:.5,poison:2,flying:0,bug:.5,rock:2},flying:{electric:.5,grass:2,fighting:2,bug:2,rock:.5},psychic:{fighting:2,poison:2,psychic:.5,bug:2,ghost:2},bug:{fire:.5,grass:2,fighting:.5,poison:.5,flying:.5,psychic:2,ghost:.5},rock:{normal:.5,fire:2,ice:2,fighting:.5,ground:.5,flying:2,bug:2},ghost:{normal:0,psychic:2,ghost:2},dragon:{dragon:2}
};
const STATUS_MOVES={
 thunderwave:{status:'par',chance:100},stunspore:{status:'par',chance:75},glare:{status:'par',chance:75},poisonpowder:{status:'poison',chance:75},toxic:{status:'toxic',chance:85},'poison-sting':{status:'poison',chance:30},poison:{status:'poison',chance:100},
 sleeppowder:{status:'sleep',chance:75},hypnosis:{status:'sleep',chance:60},sing:{status:'sleep',chance:55},lovelykiss:{status:'sleep',chance:75},spore:{status:'sleep',chance:100},darkvoid:{status:'sleep',chance:80},
 'confuse-ray':{status:'confusion',chance:100},supersonic:{status:'confusion',chance:55},'psybeam':{status:'confusion',chance:10},'water-pulse':{status:'confusion',chance:20},
 recover:{heal:50},softboiled:{heal:50},rest:{heal:100,status:'sleep'},absorb:{drain:.5},megadrain:{drain:.5},gigadrain:{drain:.5},leechlife:{drain:.5},'dream-eater':{drain:.5},
 swordsdance:{boost:'atk',amount:2},growth:{boost:'spc',amount:1},amnesia:{boost:'spc',amount:2},agility:{boost:'spe',amount:2},harden:{boost:'def',amount:1},withdraw:{boost:'def',amount:1},'defense-curl':{boost:'def',amount:1},meditate:{boost:'atk',amount:1},sharpen:{boost:'atk',amount:1},acidarmor:{boost:'def',amount:2},barrier:{boost:'def',amount:2},
 leer:{boost:'foeDef',amount:-1},tailwhip:{boost:'foeDef',amount:-1},growl:{boost:'foeAtk',amount:-1},'string-shot':{boost:'foeSpe',amount:-1},'sand-attack':{boost:'foeAcc',amount:-1},smokescreen:{boost:'foeAcc',amount:-1},kinesis:{boost:'foeAcc',amount:-1},flash:{boost:'foeAcc',amount:-1},screech:{boost:'foeDef',amount:-2},'swords-dance':{boost:'atk',amount:2},'double-team':{boost:'evasion',amount:1},minimize:{boost:'evasion',amount:1},smog:{status:'poison',chance:40},sludge:{status:'poison',chance:30},'sludge-bomb':{status:'poison',chance:30},'body-slam':{status:'par',chance:30},'lick':{status:'par',chance:30},'thunder':{status:'par',chance:10},'thunderbolt':{status:'par',chance:10},'ice-beam':{status:'freeze',chance:10},blizzard:{status:'freeze',chance:10},'flamethrower':{status:'burn',chance:10},fireblast:{status:'burn',chance:30},'ember':{status:'burn',chance:10},'rock-slide':{flinch:30},'waterfall':{flinch:20},'bite':{flinch:10},'stomp':{flinch:30},'headbutt':{flinch:30},'slash':{crit:true},'razor-leaf':{crit:true},'karate-chop':{crit:true},'crabhammer':{crit:true},'high-jump-kick':{recoil:1},'jump-kick':{recoil:1},'take-down':{recoil:.25},'double-edge':{recoil:.33},'submission':{recoil:.25},'struggle':{recoil:.25}
};
const RECOIL_MOVES=new Set(['take-down','double-edge','submission','high-jump-kick','jump-kick','struggle']);
const S={page:'home',ready:false,error:null,dex:null,gen:null,mons:[],byId:new Map(),selected:null,team:[],moves:new Map(),search:'',type:'',sort:'id',battle:null,online:null};
const app=document.querySelector('#app');
const cap=s=>String(s).split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const moveLabel=id=>cap(id.replace(/-/g,' '));
const effect=(type,target)=>(TYPE_CHART[type]||{})[target]??1;
const typeMult=(move,target)=>target.types.reduce((m,t)=>m*effect(move.type,t),1);
const stage=n=>n>=0?(2+n)/2:2/(2-n);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const randomInt=n=>Math.floor(Math.random()*n);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

async function loadData(){
 try{
  if(!window.pkmn?.dex?.Dex||!window.pkmn?.data?.Generations)throw Error('Gen I data library failed to load. Refresh once if this happens.');
  S.dex=pkmn.dex.Dex.forGen(1);S.gen=new pkmn.data.Generations(pkmn.dex.Dex).get(1);
  const arr=[];
  for(const sp of S.gen.species){if(!sp.num||sp.num>151||sp.isNonstandard)continue;arr.push({id:sp.num,name:sp.name.toLowerCase(),displayName:sp.name,types:sp.types.map(x=>x.toLowerCase()),baseStats:{hp:sp.baseStats.hp,atk:sp.baseStats.atk,def:sp.baseStats.def,spe:sp.baseStats.spe,spc:sp.baseStats.spc},sprite:SPRITE(sp.num),art:ART(sp.num),species:sp});}
  arr.sort((a,b)=>a.id-b.id);S.mons=arr;arr.forEach(m=>S.byId.set(m.id,m));
  if(arr.length!==151)throw Error(`Expected 151 Gen I Pokémon, received ${arr.length}.`);
  S.ready=true;render();
 }catch(e){S.error=e;render();}
}
async function learnset(mon){
 if(mon.learned)return mon.learned;const out=[];
 for await(const item of S.gen.learnsets.all(mon.species)){if(item.learnset)for(const [moveId] of Object.entries(item.learnset))out.push(moveId);}
 mon.learned=[...new Set(out)].filter(id=>S.gen.moves.get(id)?.exists!==false).sort((a,b)=>moveLabel(a).localeCompare(moveLabel(b)));return mon.learned;
}
function moveData(id){const m=S.gen.moves.get(id);if(!m||m.exists===false)return null;const type=GEN1_MOVE_TYPE_OVERRIDES[id]||(m.type||'Normal').toLowerCase();return{id,name:id,type,category:PHYSICAL.has(type)?'physical':'special',power:m.basePower||0,accuracy:m.accuracy===true?100:(m.accuracy||100),pp:m.pp||1};}
function maxStats(mon){const bs=mon.baseStats,dv=15,exp=65535,bonus=Math.floor(Math.sqrt(exp)/4);return{hp:Math.floor((((bs.hp+dv)*2+bonus)*LEVEL)/100)+LEVEL+10,atk:Math.floor((((bs.atk+dv)*2+bonus)*LEVEL)/100)+5,def:Math.floor((((bs.def+dv)*2+bonus)*LEVEL)/100)+5,spe:Math.floor((((bs.spe+dv)*2+bonus)*LEVEL)/100)+5,spc:Math.floor((((bs.spc+dv)*2+bonus)*LEVEL)/100)+5};}
function legalMoves(mon){return[...(mon.learned||[])].map(moveData).filter(Boolean);}
async function ensureMoves(mon){const list=await learnset(mon);if(!S.moves.has(mon.id)&&list.length>=4)S.moves.set(mon.id,list.slice(0,4));}
function filtered(){let a=S.mons.filter(m=>{const q=S.search.toLowerCase();return(!q||m.name.includes(q)||String(m.id)===q)&&(!S.type||m.types.includes(S.type));});if(S.sort==='id')a.sort((x,y)=>x.id-y.id);else a.sort((x,y)=>(y.baseStats[S.sort]||0)-(x.baseStats[S.sort]||0));return a;}

function home(){app.innerHTML=`<section class="hero"><div class="brand">GEN I COMPETITIVE ARENA</div><h1>151 Pokémon.<br><span>Your team. Your rival.</span></h1><p class="muted">Build six, choose four Red/Blue-legal moves for each, then battle locally or online. The battle rules intentionally fix the old Ghost/Psychic cartridge bug.</p><div class="row"><button class="btn primary" id="build">BUILD TEAM</button><button class="btn" id="quick">QUICK BATTLE</button></div><div class="notice">Level 50 • Gen I physical/special by move type • 151 Kanto Pokémon • 4 locked-in moves per Pokémon • <b>Ghost → Psychic = 2×</b> and <b>Psychic → Ghost = 2×</b>.</div></section><section class="panel" style="margin-top:12px"><div class="stats"><div class="stat"><b>151</b><span class="muted">Kanto</span></div><div class="stat"><b>165</b><span class="muted">Gen I moves</span></div><div class="stat"><b>6v6</b><span class="muted">teams</span></div><div class="stat"><b>4</b><span class="muted">moves each</span></div><div class="stat"><b>Lv.50</b><span class="muted">battle</span></div></div></section><section class="panel" style="margin-top:12px"><h3>Online casual PvP</h3><p class="muted">Create a private room and share the code. Player actions are written to a separate action queue, so both players cannot overwrite the same turn state.</p><div class="online"><button class="btn primary" id="create">CREATE ROOM</button><button class="btn" id="join">JOIN ROOM</button></div></section>`;}
function teamPage(){const list=filtered(),p=S.selected?S.byId.get(S.selected):null;app.innerHTML=`<section class="panel"><div class="row"><div><div class="brand">TEAM BUILDER</div><h2 style="margin:.2rem 0">Build your six</h2></div><div class="spacer"></div><span class="pill">${S.team.length}/6 Pokémon</span><button class="btn primary" id="start" ${S.team.length!==6?'disabled':''}>START LOCAL</button><button class="btn" id="create" ${S.team.length!==6?'disabled':''}>CREATE ONLINE ROOM</button></div><div class="team">${S.team.map((id,i)=>{const m=S.byId.get(id);return`<div class="slot"><span>${i+1}</span><img src="${m.sprite}"><b>${esc(m.displayName)}</b><button class="btn" data-remove="${id}">×</button></div>`;}).join('')}</div><div class="controls"><input class="input" id="search" placeholder="Search Pokémon…" value="${esc(S.search)}"><select class="select" id="filter"><option value="">All types</option>${TYPE_ORDER.map(t=>`<option ${S.type===t?'selected':''} value="${t}">${cap(t)}</option>`).join('')}</select><select class="select" id="sort"><option value="id" ${S.sort==='id'?'selected':''}>Pokédex order</option><option value="hp" ${S.sort==='hp'?'selected':''}>HP</option><option value="atk" ${S.sort==='atk'?'selected':''}>Attack</option><option value="def" ${S.sort==='def'?'selected':''}>Defense</option><option value="spc" ${S.sort==='spc'?'selected':''}>Special</option><option value="spe" ${S.sort==='spe'?'selected':''}>Speed</option></select></div><div class="grid">${list.map(m=>`<button class="dex ${S.selected===m.id?'selected':''}" data-pick="${m.id}"><span class="num">#${String(m.id).padStart(3,'0')}</span><img src="${m.sprite}" alt="${esc(m.displayName)}"><b>${esc(m.displayName)}</b><div>${m.types.map(t=>`<span class="tag">${cap(t)}</span>`).join(' / ')}</div></button>`).join('')}</div>${p?detail(p):''}</section>`;}
function detail(p){const chosen=S.moves.get(p.id)||[],stats=p.baseStats;return`<div class="detail"><div class="portrait"><img src="${p.art}" alt="${esc(p.displayName)}"><strong>#${String(p.id).padStart(3,'0')} ${esc(p.displayName)}</strong><div>${p.types.map(t=>`<span class="pill">${cap(t)}</span>`).join('')}</div><button class="btn primary" id="add" ${S.team.includes(p.id)||S.team.length>=6?'disabled':''}>${S.team.includes(p.id)?'IN TEAM':'ADD TO TEAM'}</button></div><div><div class="stats"><div class="stat"><b>${stats.hp}</b><span class="muted">HP</span></div><div class="stat"><b>${stats.atk}</b><span class="muted">ATK</span></div><div class="stat"><b>${stats.def}</b><span class="muted">DEF</span></div><div class="stat"><b>${stats.spc}</b><span class="muted">SPC</span></div><div class="stat"><b>${stats.spe}</b><span class="muted">SPE</span></div></div><h3>Red/Blue legal moves <span class="muted small">(${chosen.length}/4 selected)</span></h3><div class="moves">${legalMoves(p).map(m=>`<div class="move ${chosen.includes(m.id)?'selected':''}" data-move="${m.id}" data-mon="${p.id}"><b>${moveLabel(m.id)}</b><div class="small muted">${cap(m.type)} • ${m.power||'Status'} • ${m.accuracy}% • ${m.pp} PP</div></div>`).join('')}</div></div></div>`;}

function buildMon(mon,chosen){const st=maxStats(mon),ids=chosen.slice(0,4);return{id:mon.id,name:mon.name,displayName:mon.displayName,types:mon.types,max:st,hp:st.hp,status:null,statusTurns:0,boosts:{atk:0,def:0,spe:0,spc:0,acc:0,evasion:0},moves:ids.map(moveData).filter(Boolean),pp:Object.fromEntries(ids.map(x=>[x,moveData(x)?.pp||1]))};}
function cloneTeam(team){return team.map(x=>({...x,max:{...x.max},boosts:{...x.boosts},moves:x.moves.map(m=>({...m})),pp:{...x.pp}}));}
function effectiveStat(mon,key){const raw=mon.max[key]||0;return raw*stage(mon.boosts[key]||0);}
function accuracyMultiplier(mon){return stage(mon.boosts.acc||0);}
function applyStatus(mon,status){if(mon.status&&status!=='confusion')return false;if(['poison','toxic'].includes(status)&&mon.types.includes('poison'))return false;if(status==='par'&&mon.types.includes('electric'))return false;if(status==='burn'&&mon.types.includes('fire'))return false;if(status==='freeze'&&mon.types.includes('ice'))return false;if(status==='sleep'){mon.status='sleep';mon.statusTurns=2+randomInt(3);}else if(status==='confusion'){mon.status='confusion';mon.statusTurns=2+randomInt(3);}else mon.status=status;return true;}
function damage(att,def,mv){const e=typeMult(mv,def);if(e===0||!mv.power)return{dmg:0,e,crit:false};const atkKey=PHYSICAL.has(mv.type)?'atk':'spc',defKey=PHYSICAL.has(mv.type)?'def':'spc';let A=Math.floor(effectiveStat(att,atkKey)),D=Math.max(1,Math.floor(effectiveStat(def,defKey)));let crit=Math.random()<.0625;if(STATUS_MOVES[mv.id]?.crit)crit=true;if(crit){A=Math.floor(att.max[atkKey]);D=Math.max(1,Math.floor(def.max[defKey]));}let x=Math.floor(Math.floor(2*LEVEL/5+2)*mv.power*A/D/50)+2;const stab=att.types.includes(mv.type)?1.5:1;const rand=(217+randomInt(39))/255;let dmg=Math.floor(x*stab*e*rand);if(dmg<1&&e>0)dmg=1;return{dmg,e,crit};}
function canAct(mon,log){if(mon.status==='sleep'){if(mon.statusTurns>0){mon.statusTurns--;log(`${mon.displayName} is asleep.`);return false;}mon.status=null;log(`${mon.displayName} woke up!`);}if(mon.status==='par'&&Math.random()<.25){log(`${mon.displayName} is fully paralyzed.`);return false;}if(mon.status==='freeze'){if(Math.random()<.2){mon.status=null;log(`${mon.displayName} thawed out!`);}else{log(`${mon.displayName} is frozen solid.`);return false;}}if(mon.status==='confusion'){if(mon.statusTurns>0){mon.statusTurns--;if(Math.random()<.5){const self=Math.max(1,Math.floor((Math.floor(2*LEVEL/5+2)*40*effectiveStat(mon,'atk')/Math.max(1,effectiveStat(mon,'def'))/50)+2));mon.hp=Math.max(0,mon.hp-self);log(`${mon.displayName} hurt itself in confusion!`);return false;}}else{mon.status=null;log(`${mon.displayName} snapped out of confusion!`);}}return true;}
function endTurn(mon,log){if(mon.status==='poison'||mon.status==='toxic'){const d=Math.max(1,Math.floor(mon.max.hp/16));mon.hp=Math.max(0,mon.hp-d);log(`${mon.displayName} took ${d} poison damage.`);}}
function resolveMove(att,def,mv,log){if(!mv||!canAct(att,log))return;if(att.pp[mv.id]<=0){log(`${moveLabel(mv.id)} has no PP!`);return;}att.pp[mv.id]--;const acc=clamp(mv.accuracy*accuracyMultiplier(att),1,100);if(Math.random()*100>=acc){log(`${att.displayName} used ${moveLabel(mv.id)} — missed!`);return;}const spec=STATUS_MOVES[mv.id];if(spec?.status&&Math.random()*100<=(spec.chance??100)){if(applyStatus(def,spec.status))log(`${def.displayName} is ${spec.status==='par'?'paralyzed':spec.status==='sleep'?'asleep':spec.status==='confusion'?'confused':spec.status==='freeze'?'frozen':spec.status==='burn'?'burned':spec.status==='toxic'?'badly poisoned':'poisoned'}!`);}if(spec?.boost){const target=spec.boost.startsWith('foe')?def:att;const key=spec.boost.replace('foe','');if(key==='special'||key==='spc')target.boosts.spc=clamp(target.boosts.spc+spec.amount,-6,6);else if(key==='acc'||key==='evasion')target.boosts[key]=clamp(target.boosts[key]+spec.amount,-6,6);else target.boosts[key]=clamp(target.boosts[key]+spec.amount,-6,6);log(`${att.displayName} used ${moveLabel(mv.id)}.`);}if(spec?.heal){const healed=Math.min(att.max.hp-att.hp,Math.floor(att.max.hp*(spec.heal/100)));att.hp+=healed;log(`${att.displayName} recovered ${healed} HP.`);}if(mv.id==='rest'&&att.hp>0){att.hp=att.max.hp;att.status='sleep';att.statusTurns=2+randomInt(3);log(`${att.displayName} went to sleep and fully healed.`);}if(mv.power){const r=damage(att,def,mv);def.hp=Math.max(0,def.hp-r.dmg);let msg=`${att.displayName} used ${moveLabel(mv.id)} — ${r.dmg} damage.`;if(r.crit)msg+=' CRITICAL!';if(r.e===0)msg+=' NO EFFECT!';else if(r.e>1)msg+=' SUPER EFFECTIVE!';else if(r.e<1)msg+=' NOT VERY EFFECTIVE.';log(msg);if(spec?.drain&&r.dmg)att.hp=Math.min(att.max.hp,att.hp+Math.floor(r.dmg*spec.drain));if(spec?.recoil&&r.dmg)att.hp=Math.max(0,att.hp-Math.max(1,Math.floor(r.dmg*spec.recoil)));}}
function chooseEnemyMove(mon){const usable=mon.moves.filter(m=>mon.pp[m.id]>0);return usable.length?usable[randomInt(usable.length)]:mon.moves[0];}
function legalSwitch(team,index,activeIndex){return Number.isInteger(index)&&index>=0&&index<team.length&&index!==activeIndex&&team[index].hp>0;}
function finishFaint(b,side,log){const team=side==='my'?b.my:b.foe;const activeIndex=side==='my'?b.mi:b.fi;const mon=team[activeIndex];if(mon.hp>0)return null;log.push(`${mon.displayName} fainted!`);if(team.every(x=>x.hp<=0)){b.over=true;log.push(side==='my'?'You lose!':'You win!');return null;}if(side==='my')b.waitingSwitch=true;else{const n=team.findIndex(x=>x.hp>0);if(n>=0)b.fi=n;log.push(`Opponent sent out ${team[b.fi].displayName}.`);}return null;}
function doTurn(idx){const b=S.battle;if(b.over||b.waitingSwitch)return;const a=active('my'),d=active('foe'),mv=a.moves[idx],em=chooseEnemyMove(d);if(!mv||a.pp[mv.id]<=0)return;b.log.push(`Turn ${b.turn}`);const order=[];const as=effectiveStat(a,'spe')*(a.status==='par'?.25:1),ds=effectiveStat(d,'spe')*(d.status==='par'?.25:1);if(as>ds||(as===ds&&Math.random()<.5))order.push([a,d,mv],[d,a,em]);else order.push([d,a,em],[a,d,mv]);for(const[x,y,m]of order){if(x.hp<=0||y.hp<=0)continue;resolveMove(x,y,m,b.log.push.bind(b.log));if(y.hp<=0)break;}endTurn(a,b.log.push.bind(b.log));endTurn(d,b.log.push.bind(b.log));finishFaint(b,'my',b.log);if(!b.over&&!b.waitingSwitch)finishFaint(b,'foe',b.log);b.turn++;render();}
function manualSwitch(index){const b=S.battle;if(b.over||!legalSwitch(b.my,index,b.mi))return;b.mi=index;b.waitingSwitch=false;b.log.push(`You switched to ${b.my[index].displayName}.`);render();}
function active(side){return side==='my'?S.battle.my[S.battle.mi]:S.battle.foe[S.battle.fi];}
function startLocal(){if(S.team.length!==6){alert('Choose six Pokémon first.');return;}for(const id of S.team){const c=S.moves.get(id)||[];if(c.length!==4){alert(`${S.byId.get(id).displayName} needs exactly four moves.`);return;}}const foePool=S.mons.filter(m=>!S.team.includes(m.id)),foe=[];while(foe.length<6){const m=foePool[randomInt(foePool.length)];if(!foe.some(x=>x.id===m.id)){const moves=legalMoves(m).slice(0,4).map(x=>x.id);foe.push(buildMon(m,moves));}}S.battle={mode:'local',my:S.team.map(id=>buildMon(S.byId.get(id),S.moves.get(id))),foe,mi:0,fi:0,turn:1,log:['Battle started!'],over:false,waitingSwitch:false};nav('battle');}

function serializeMon(m){return{id:m.id,hp:m.hp,status:m.status,statusTurns:m.statusTurns,boosts:m.boosts,pp:m.pp,max:m.max,moves:m.moves.map(x=>x.id)};}
function hydrateBattleTeam(arr){return(arr||[]).map(x=>{const base=S.byId.get(x.id);const m=buildMon(base,x.moves||[]);m.hp=x.hp??m.hp;m.status=x.status??null;m.statusTurns=x.statusTurns??0;m.boosts={...m.boosts,...(x.boosts||{})};m.pp={...m.pp,...(x.pp||{})};return m;});}
function makeTeamPayload(){return S.team.map(id=>({id,moves:S.moves.get(id)}));}
function hydrateChosenTeam(payload){return(payload||[]).map(x=>buildMon(S.byId.get(x.id),x.moves||[]));}

function battlePage(){const b=S.battle;if(!b){app.innerHTML=`<section class="hero"><h2>No battle loaded</h2><button class="btn primary" id="team">BUILD TEAM</button></section>`;return;}const a=active('my'),d=active('foe');const fighter=m=>{const pct=Math.max(0,m.hp/m.max.hp*100);return`<div class="fighter"><div class="row"><strong>${esc(m.displayName)}</strong><span class="spacer">Lv.50</span></div><img src="${SPRITE(m.id)}"><div class="hp ${pct<25?'low':''}"><i style="width:${pct}%"></i></div><div class="muted">${m.hp}/${m.max.hp} HP • ${m.types.map(cap).join(' / ')}</div>${m.status?`<div class="pill">${m.status.toUpperCase()}</div>`:''}</div>`;};let body='';if(b.over)body=`<div class="notice result ${b.my.every(x=>x.hp<=0)?'lose':'win'}">${b.my.every(x=>x.hp<=0)?'💀 Defeat':'🏆 Victory'} <button class="btn primary" id="rematch">NEW LOCAL BATTLE</button></div>`;else if(b.mode==='online'&&b.waitingRemote)body=`<div class="notice">Waiting for the other player…</div>`;else if(b.waitingSwitch)body=`<div class="notice"><b>Choose your next Pokémon.</b></div><div class="bench">${b.my.map((x,i)=>`<button class="btn" data-switch="${i}" ${x.hp<=0?'disabled':''}>${esc(x.displayName)} ${x.hp}/${x.max.hp}</button>`).join('')}</div>`;else body=`<div class="actions">${a.moves.map((m,i)=>`<button class="movebtn" data-act="${i}" ${a.pp[m.id]<=0?'disabled':''}><strong>${moveLabel(m.id)}</strong><div class="muted">${cap(m.type)} • ${m.power||'Status'} • ${m.accuracy}% • ${a.pp[m.id]} PP</div></button>`).join('')}</div><div class="bench">${b.my.map((x,i)=>`<button class="btn" data-switch="${i}" disabled>${esc(x.displayName)} ${x.hp}/${x.max.hp}</button>`).join('')}</div>`;app.innerHTML=`<section class="panel"><div class="row"><div><div class="brand">${b.mode==='online'?'ONLINE MATCH':'LOCAL BATTLE'}</div><h2 style="margin:.2rem 0">Turn ${b.turn}</h2></div><div class="spacer"></div><button class="btn danger" id="forfeit">FORFEIT</button></div><div class="battlegrid" style="margin-top:10px">${fighter(d)}${fighter(a)}</div><div class="log">${b.log.slice(-20).map(x=>`<div>${esc(x)}</div>`).join('')}</div>${body}</section>`;}

async function auth(){const sb=createClient(SUPABASE_URL,SUPABASE_KEY);const{data,error}=await sb.auth.signInAnonymously();if(error)throw error;return{sb,user:data.user};}
async function createOnline(){if(S.team.length!==6){alert('Build a six-Pokémon team first.');nav('team');return;}for(const id of S.team){await ensureMoves(S.byId.get(id));if((S.moves.get(id)||[]).length!==4)throw Error(`${S.byId.get(id).displayName} needs exactly four moves.`);}const{sb,user}=await auth(),code=Math.random().toString(36).slice(2,8).toUpperCase(),team=makeTeamPayload();const{data:room,error}=await sb.from('pvp_rooms').insert({code,host_id:user.id,status:'waiting',battle_state:{hostTeam:team,guestTeam:null,hostReady:false,guestReady:false,turn:1,result:null,hostIndex:0,guestIndex:0}}).select().single();if(error)throw error;S.online={sb,user,roomId:room.id,code,role:'host',channel:null};subscribeOnline();onlineLobby();}
async function joinOnline(){if(S.team.length!==6){alert('Build a six-Pokémon team first.');nav('team');return;}const code=(prompt('Enter room code:')||'').trim().toUpperCase();if(!code)return;for(const id of S.team){await ensureMoves(S.byId.get(id));if((S.moves.get(id)||[]).length!==4)throw Error(`${S.byId.get(id).displayName} needs exactly four moves.`);}const{sb,user}=await auth(),{data:room,error}=await sb.from('pvp_rooms').select('*').eq('code',code).maybeSingle();if(error)throw error;if(!room)throw Error('Room not found.');if(room.guest_id)throw Error('That room is already full.');const team=makeTeamPayload();const{data:updated,error:ue}=await sb.from('pvp_rooms').update({guest_id:user.id,status:'active',battle_state:{...(room.battle_state||{}),guestTeam:team}}).eq('id',room.id).is('guest_id',null).select().single();if(ue)throw ue;if(!updated)throw Error('Someone else joined that room first.');S.online={sb,user,roomId:room.id,code,role:'guest',channel:null};subscribeOnline();onlineLobby();}
function subscribeOnline(){const o=S.online;o.channel=o.sb.channel(`pvp-${o.roomId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'pvp_rooms',filter:`id=eq.${o.roomId}`},payload=>{o.room=payload.new;const st=payload.new.battle_state||{};if(payload.new.status==='battle'||payload.new.status==='finished')loadOnlineBattle(payload.new);else onlineLobby();}).on('postgres_changes',{event:'INSERT',schema:'public',table:'pvp_actions',filter:`room_id=eq.${o.roomId}`},async payload=>{if(o.role==='host')await maybeResolveOnline(payload.new.room_id);}).on('postgres_changes',{event:'DELETE',schema:'public',table:'pvp_rooms',filter:`id=eq.${o.roomId}`},()=>{S.online=null;S.battle=null;nav('home');}).subscribe();}
async function onlineLobby(){const o=S.online;const{data,error}=await o.sb.from('pvp_rooms').select('*').eq('id',o.roomId).single();if(error)throw error;o.room=data;const st=data.battle_state||{};const ready=o.role==='host'?!!st.hostReady:!!st.guestReady;app.innerHTML=`<section class="panel"><div class="brand">ONLINE ROOM</div><div class="room">${o.code}</div><p class="muted">Share this code. Player 2 joins from another browser/device.</p><div class="notice">${data.guest_id?'Player 2 connected.':'Waiting for Player 2…'} ${ready?'<span class="check">READY ✓</span>':''}</div><div class="row"><button class="btn primary" id="readyOnline" ${!data.guest_id||ready?'disabled':''}>${ready?'READY ✓':'READY UP'}</button><button class="btn" id="copy">COPY CODE</button><button class="btn danger" id="leaveOnline">LEAVE</button></div></section>`;}
async function readyOnline(){const o=S.online,{data,error}=await o.sb.from('pvp_rooms').select('*').eq('id',o.roomId).single();if(error)throw error;const st={...(data.battle_state||{})};if(o.role==='host')st.hostReady=true;else st.guestReady=true;const both=!!st.hostReady&&!!st.guestReady&&!!st.hostTeam&&!!st.guestTeam;const{error:e}=await o.sb.from('pvp_rooms').update({battle_state:st,status:both?'battle':'active'}).eq('id',o.roomId);if(e)throw e;if(both)loadOnlineBattle({...data,status:'battle',battle_state:st});}
function loadOnlineBattle(room){const o=S.online,st=room.battle_state||{};if(!st.hostTeam||!st.guestTeam)return;const host=st.hostBattle?hydrateBattleTeam(st.hostBattle):hydrateChosenTeam(st.hostTeam),guest=st.guestBattle?hydrateBattleTeam(st.guestBattle):hydrateChosenTeam(st.guestTeam),mine=o.role==='host'?host:guest,foe=o.role==='host'?guest:host,mi=o.role==='host'?(st.hostIndex??0):(st.guestIndex??0),fi=o.role==='host'?(st.guestIndex??0):(st.hostIndex??0);S.battle={mode:'online',my:mine,foe,mi,fi,turn:st.turn||1,log:st.log||['Online battle started!'],over:!!st.result,result:st.result||null,waitingSwitch:mine[mi]?.hp<=0&&!st.result,waitingRemote:false,remoteTurn:st.turn||1};nav('battle');}
async function submitOnlineAction(action){const o=S.online,b=S.battle;if(!o||!b||b.over||b.waitingRemote)return;const{data:room,error}=await o.sb.from('pvp_rooms').select('*').eq('id',o.roomId).single();if(error)throw error;const st=room.battle_state||{};if(st.turn!==b.turn)return;if(action.type==='move'){const a=active('my');const mv=a.moves[action.index];if(!mv||a.pp[mv.id]<=0)return;}if(action.type==='switch'&&!legalSwitch(b.my,action.index,b.mi))return;const{error:ie}=await o.sb.from('pvp_actions').insert({room_id:o.roomId,player_id:o.user.id,turn:b.turn,action});if(ie){if(ie.code==='23505')return;throw ie;}b.waitingRemote=true;render();}
async function maybeResolveOnline(roomId){
 const o=S.online;if(!o||o.role!=='host')return;
 const {data:room,error}=await o.sb.from('pvp_rooms').select('*').eq('id',roomId).single();if(error)throw error;
 const st=room.battle_state||{};if(room.status!=='battle'||st.result)return;
 const {data:acts,error:ae}=await o.sb.from('pvp_actions').select('*').eq('room_id',roomId).eq('turn',st.turn).order('created_at');if(ae)throw ae;
 const byRole={};for(const x of acts||[]){const role=x.player_id===room.host_id?'host':x.player_id===room.guest_id?'guest':null;if(role&&!byRole[role])byRole[role]=x.action;}
 if(!byRole.host||!byRole.guest)return;
 const host=hydrateBattleTeam(st.hostBattle||st.hostTeam),guest=hydrateBattleTeam(st.guestBattle||st.guestTeam);let hi=st.hostIndex??0,gi=st.guestIndex??0;
 const h=host[hi],g=guest[gi],log=[...(st.log||[]),`Turn ${st.turn}`];
 const hostForced=h.hp<=0,guestForced=g.hp<=0;
 const validAction=(team,idx,action,forced)=>action?.type==='switch'?legalSwitch(team,action.index,idx):(!forced&&action?.type==='move'&&team[idx]?.moves?.[action.index]&&team[idx].pp[team[idx].moves[action.index].id]>0);
 if(!validAction(host,hi,byRole.host,hostForced)||!validAction(guest,gi,byRole.guest,guestForced)){await o.sb.from('pvp_actions').delete().eq('room_id',roomId).eq('turn',st.turn);return;}
 const switchFirst=(team,idx,action,label)=>{if(action.type!=='switch')return idx;const next=action.index;log.push(`${label} switched to ${team[next].displayName}.`);return next;};
 if(hostForced)hi=switchFirst(host,hi,byRole.host,'Player 1');
 if(guestForced)gi=switchFirst(guest,gi,byRole.guest,'Player 2');
 const ha=byRole.host,ga=byRole.guest;
 const execute=(actor,target,action)=>{if(action.type==='move'){const mv=actor.moves[action.index];if(mv)resolveMove(actor,target,mv,log.push.bind(log));}};
 if(hostForced&&guestForced){
   // Both sides were knocked out at the end of the previous turn: both switches resolve before any attack.
 } else if(hostForced&&!guestForced){
   execute(guest[gi],host[hi],ga);
 } else if(guestForced&&!hostForced){
   execute(host[hi],guest[gi],ha);
 } else {
   const a=host[hi],d=guest[gi],first=ha.type==='switch'?true:ga.type==='switch'?false:(effectiveStat(a,'spe')*(a.status==='par'?.25:1)>effectiveStat(d,'spe')*(d.status==='par'?.25:1)||(effectiveStat(a,'spe')===effectiveStat(d,'spe')&&Math.random()<.5));
   if(first){execute(host[hi],guest[gi],ha);if(guest[gi].hp>0)execute(guest[gi],host[hi],ga);}else{execute(guest[gi],host[hi],ga);if(host[hi].hp>0)execute(host[hi],guest[gi],ha);}
 }
 const ah=host[hi],ag=guest[gi];endTurn(ah,log.push.bind(log));endTurn(ag,log.push.bind(log));
 let result=null;if(host.every(x=>x.hp<=0))result='guest';else if(guest.every(x=>x.hp<=0))result='host';
 const next={...st,turn:st.turn+1,result,hostIndex:hi,guestIndex:gi,hostBattle:host.map(serializeMon),guestBattle:guest.map(serializeMon),log};
 const {error:ue}=await o.sb.from('pvp_rooms').update({battle_state:next,status:result?'finished':'battle'}).eq('id',roomId);if(ue)throw ue;
 await o.sb.from('pvp_actions').delete().eq('room_id',roomId).eq('turn',st.turn);
}
async function leaveOnline(){const o=S.online;if(!o)return;await o.sb.from('pvp_rooms').delete().eq('id',o.roomId);S.online=null;S.battle=null;nav('home');}

function nav(p){S.page=p;render();}
function render(){if(!S.ready){app.innerHTML=S.error?`<section class="hero"><h1>Data load failed.</h1><p class="muted">${esc(S.error.message)}</p><button class="btn primary" id="retry">RETRY</button></section>`:`<section class="hero"><div class="brand">LOADING VERIFIED GEN I DATA…</div><h1>Preparing the <span>Kanto roster</span></h1><p class="muted">Loading 151 Pokémon, Gen I stats/types/moves and legal learnsets.</p></section>`;return;}if(S.page==='home')home();else if(S.page==='team')teamPage();else battlePage();}

document.querySelector('.top').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='home')nav('home');if(b.id==='team')nav('team');if(b.id==='battle')S.battle?nav('battle'):nav('team');});
app.addEventListener('input',e=>{if(e.target.id==='search'){S.search=e.target.value;render();}});
app.addEventListener('change',e=>{if(e.target.id==='filter'){S.type=e.target.value;render();}if(e.target.id==='sort'){S.sort=e.target.value;render();}});
app.addEventListener('click',async e=>{const b=e.target.closest('button,.move');if(!b)return;try{
 if(b.id==='build')nav('team');
 else if(b.id==='quick'){if(S.team.length!==6){S.team=[1,4,7,25,59,94];for(const id of S.team)await ensureMoves(S.byId.get(id));}startLocal();}
 else if(b.dataset.pick){S.selected=+b.dataset.pick;await ensureMoves(S.byId.get(S.selected));render();}
 else if(b.dataset.remove){S.team=S.team.filter(x=>x!==+b.dataset.remove);render();}
 else if(b.id==='add'){if(S.selected&&!S.team.includes(S.selected)&&S.team.length<6){S.team.push(S.selected);await ensureMoves(S.byId.get(S.selected));render();}}
 else if(b.dataset.move){const id=+b.dataset.mon,n=b.dataset.move,arr=S.moves.get(id)||[];if(arr.includes(n))S.moves.set(id,arr.filter(x=>x!==n));else if(arr.length<4)S.moves.set(id,[...arr,n]);render();}
 else if(b.id==='start')startLocal();else if(b.id==='create')await createOnline();else if(b.id==='join')await joinOnline();else if(b.id==='readyOnline')await readyOnline();else if(b.id==='copy'){await navigator.clipboard?.writeText(S.online.code);alert('Room code copied: '+S.online.code);}else if(b.id==='leaveOnline')await leaveOnline();
 else if(b.dataset.act){if(S.battle.mode==='online')await submitOnlineAction({type:'move',index:+b.dataset.act});else doTurn(+b.dataset.act);}
 else if(b.dataset.switch){if(S.battle.mode==='online')await submitOnlineAction({type:'switch',index:+b.dataset.switch});else if(S.battle.waitingSwitch)manualSwitch(+b.dataset.switch);}
 else if(b.id==='forfeit'){if(S.battle.mode==='online'&&S.online)await leaveOnline();else{S.battle.over=true;render();}}
 else if(b.id==='rematch')startLocal();else if(b.id==='retry')location.reload();
 }catch(err){console.error(err);alert(err.message||String(err));}});
loadData();
