import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import vm from 'node:vm';
const root=new URL('.',import.meta.url);
const app=fs.readFileSync(new URL('./app.mjs',root),'utf8');
const assert=(v,msg)=>{if(!v)throw new Error(msg)};
execFileSync(process.execPath,['--check','app.mjs'],{cwd:new URL('.',import.meta.url)});
for(const needle of ['function maxStats','function legalMoves','async function ensureMoves','async function learnset','arr.length!==151','expected 165 moves'])assert(app.includes(needle),`Missing runtime helper: ${needle}`);
for(const [move,type] of Object.entries({bite:'normal',gust:'normal','karate-chop':'normal','sand-attack':'ground','razor-wind':'normal',struggle:'normal'}))assert(app.includes(`${move}:'${type}'`)||app.includes(`'${move}':'${type}'`),`${move} override missing`);
assert(app.includes("ghost:{normal:0,psychic:2,ghost:2}"),'Ghost chart');
assert(app.includes("psychic:{fighting:2,poison:2,psychic:.5,bug:2,ghost:2}"),'Psychic chart');
assert(!app.includes("const list=(S.mons||[]).slice(0,4)"),'First-four fallback');
assert(app.includes('raw?.learnset || raw?.data?.learnset || raw || {}'),'Robust learnset shape handling');
const stage=n=>n>=0?(2+n)/2:2/(2-n);
assert(stage(6)===4&&stage(-6)===.25,'Stage formula');
const crit=(base,high=false,focus=false)=>Math.min(1,(base*100/512/100)*(high?8:(focus?4:1)));
assert(Math.abs(crit(110)-0.21484375)<1e-12,'Tauros crit');
assert(crit(100,true)===1,'High crit cap');
// Execute engine helpers in a sandbox with browser wiring removed.
let src=app.replace(/^import .*?;\n/,'');
const cut=src.indexOf("document.querySelector('.top').addEventListener");
src=src.slice(0,cut);
const sandbox={console,alert:()=>{},setTimeout,window:{},document:{querySelector(){return {addEventListener(){},innerHTML:''}},querySelectorAll(){return[]}},Math:Object.create(Math)};
sandbox.Math.random=()=>0.5;
sandbox.pkmn={};
vm.createContext(sandbox);
// Provide a minimal DOM app object used by constants/functions parsed above.
sandbox.document.querySelector=()=>({addEventListener(){},innerHTML:''});
vm.runInContext(src+`\nthis.__test={stage,damage,critChance,resolveMove,maxStats,buildMon,effect,typeMult};`,sandbox);
const T=sandbox.__test;
function mon(id,name,types,bs){const m={id,name:name.toLowerCase(),displayName:name,types,baseStats:bs,baseSpeed:bs.spe,status:null,statusTurns:0,toxicCounter:0,boosts:{atk:0,def:0,spe:0,spc:0,acc:0,evasion:0},volatile:{},leechSeed:null,lastHit:null,pp:{}};m.max=T.maxStats(m);m.hp=m.max.hp;return m;}
function move(id,type,power,accuracy=100,pp=20,extra={}){return {id,type,category:['normal','fighting','flying','poison','ground','rock','bug','ghost'].includes(type)?'physical':'special',power,accuracy,pp,priority:0,...extra};}
const c=mon(6,'Charizard',['fire','flying'],{hp:78,atk:84,def:78,spe:100,spc:85});
const v=mon(3,'Venusaur',['grass','poison'],{hp:80,atk:82,def:83,spe:80,spc:100});
const g=mon(94,'Gengar',['ghost','poison'],{hp:60,atk:65,def:60,spe:110,spc:130});
assert(T.effect('normal','ghost')===0,'Normal/Ghost');
assert(T.effect('ghost','psychic')===2&&T.effect('psychic','ghost')===2,'Ghost/Psychic custom rule');
const fb=move('fire-blast','fire',120,85); c.pp[fb.id]=5;
const r1=T.damage(c,v,fb); assert(r1.dmg>0&&r1.e===2,'Fire Blast damage/effectiveness');
const bs=move('body-slam','normal',85); c.pp[bs.id]=15; const r2=T.damage(c,g,bs); assert(r2.dmg===0&&r2.e===0,'Normal immune to Ghost');
const t=move('thunderbolt','electric',95); c.pp[t.id]=15; const r3=T.damage(c,v,t); assert(r3.e===0.5,'Electric/Grass resistance');
const normal=move('body-slam','normal',85,100,15); v.pp[normal.id]=15; const before=v.hp; T.resolveMove(c,v,normal,()=>{}); assert(v.hp<before,'Move resolves damage'); assert(c.pp[normal.id]===14,'PP decrements');
const accmove=move('high-jump-kick','fighting',85,1,20); c.pp[accmove.id]=20; sandbox.Math.random=()=>0.99; const hp=c.hp; T.resolveMove(c,v,accmove,()=>{}); assert(c.hp===hp-1,'HJK miss crash');
console.log('Kanto PvP V15 full diagnostics: PASS');
console.log('Syntax: PASS');
console.log('Runtime helper presence: PASS');
console.log('Type effectiveness: PASS');
console.log('Crit model: PASS');
console.log('Damage and PP smoke test: PASS');
console.log('Miss/crash smoke test: PASS');
